services:
  
  # general
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    #zapis
#    volumes:
#      - ../volumes/rabbitmq/data/:/var/lib/rabbitmq
#      - ../volumes/rabbitmq/log/:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
        
  
  sql-server-db:
    container_name: sql
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "zaq1@WSX"
      ACCEPT_EULA: "Y"
